trigger:
  branches:
    include: 
    - EgsPublisher
    - master
  paths:
    include:
      - azure-event-grid/custom-events-with-functions-csharp/azure-resources/*

variables:
- group: pategs

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: az --version
  displayName: 'Checking version'


- script: |
    pwd
    ls -R
    echo $(ResourceGroup)
    echo $(Location)
    echo $(jq --version)
  displayName: 'Checking environment'

- task: AzureCLI@2
  inputs:
    displayName: 'Pre template deployment script'
    azureSubscription: '$(Subscription)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'azure-event-grid/custom-events-with-functions-csharp/azure-resources/template-deployment.sh'
    arguments: '$(ResourceGroup) $(Location) $(KeyVaultName) $(KeyVaultOwnerObjectID)'
