trigger:
  branches:
    include: 
    - EgsPublisher
    - master
  paths:
    include:
      - azure-event-grid/custom-events-with-functions-csharp/EgsPublisher/*

variables:
- group: pategs

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    dotnet restore ./azure-event-grid/custom-events-with-functions-csharp/EgsPublisher/EgsPublisher.csproj
    dotnet build ./azure-event-grid/custom-events-with-functions-csharp/EgsPublisher/EgsPublisher.csproj