# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- keyvault

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Personal Azure Training(05c25b78-003c-49ef-8f02-b24ca4aca086)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'azure-event-grid/custom-events-with-functions-csharp/azure-resources/pre-template-deployment.sh'
    arguments: 'MyResourceGroup "North Europe"'
