name: aadb2c-webapp-webapi

on:
  push:
    branches: [ b2c-webapp-webapi ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -name: Log location
    run: pwd
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 5.0.100
#    - name: Install dependencies
#      run: dotnet restore ../../aad-b2c/webapp-webapi/code/aadb2c-webapp-webapi.csproj
#    - name: Build
#      run: dotnet build --configuration Release --no-restore ../../aad-b2c/webapp-webapi/code/aadb2c-webapp-webapi.csproj
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
