name: aadb2c-webapp-webapi

on:
  push:
    branches: [ b2c-webapp-webapi ]
  pull_request:
    branches: [ master ]

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: samples-and-demos

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log location
      run: pwd 
    
    # Check out code
    - uses: actions/checkout@v2
    
    # Set up .net core.
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    
    # Install the dependencies
    - name: Install dependencies
      run: dotnet restore ./aad-b2c/webapp-webapi/code/webapp/aadb2c-webapp-webapi.csproj

    # Build the solution
    - name: Build
      run: dotnet build --configuration Release --no-restore ./aad-b2c/webapp-webapi/code/webapp/aadb2c-webapp-webapi.csproj

    # Log in to Azure
    - uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: $GITHUB_WORKSPACE/aad-b2c/webapp-webapi/azuredeploy.json
          parameters: $GITHUB_WORKSPACE/aad-b2c/webapp-webapi/azuredeploy-parameters.json